services:
  grmn-server:
    build:
      context: .
    container_name: grmn-server
    hostname: grmn-server
    ports:
      - 8088:8080
    volumes:
      - /home/florian/work/grmn/activities:/tmp/activities
